### ISSUE TITLE
Připomínky

### ISSUE THREAD

**Issue by marhaupt** [L-uss/registrace-zadani#1]
Ahoj, poprosím **opravit následující věci** abych mohl úkol s klidným svědomím uznat:
- [x]  V zadání je _Budeme chtít, aby se ve formuláři automaticky vyplnilo políčko User Name, pokud je User Name prázdné a pokud uživatel zadá validní email._, ale tobě se přepisuje i již vyplněné uživatelské jméno. Tipuju, že by mělo stačit v metodě `handleChangeEmail` smazat tu else větev.
- [x] `form` by měl mít `onSubmit`, ne `onClick` https://github.com/L-uss/registrace-zadani/blob/14b2ad332a214e69240894690817dac64ecbb651/src/components/Registration/Registration.jsx#L28 Takhle se `handleInput` (což není ideální název, spíše `handleSubmit` nebo tak) provolá i klikáním mnohem dříve.

Další věci upravovat již nemusíš, jsou to spíš rady:

- K CSS ses počítám nedostala, nevadí, o tom úkol nebyl. Ale příště zkus aspoň nějaký základ. A pokud  tě stylování nebaví nebo na něj čas obecně nemáš (u takových úkolů to úplně chápu), hoď tam nějakou již existující šablonu, která přestyluje např. inputy atp. Sám mám rád [Skeleton](http://getskeleton.com/) (stačí stáhnout a importovat css soubory jako by byly tvoje), ale určitě bys našla alternativy.

**Comment by L-uss** [comment]
Ďakujem za pripomienky. Opravila som všetko okrem css, na to som nemala čas. Ďakujem za tip, budem sa snažiť v ďalšom úkole aspoň nejaké to css nastaviť.

**Comment by marhaupt** [comment]
Díky za rychlou opravu 👍
